apiVersion: apps/v1
kind: Deployment
metadata:
  name: klokke
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: klokke
    spec:
      containers:
      - name: klokke
        image: runarh/klokke:v1.0.0
        ports:
        - name: http
          containerPort: 8084
          protocol: TCP